version: '3.8'

services:
  mongodb:
    container_name: silice-mongodb
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: recibos_db
    volumes:
      - mongodb_data:/data/db

  backend:
    container_name: silice-backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
      - ./.env:/usr/src/app/.env
    command: npm run start:dev
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: payment-api-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mongodb_data:
  rabbitmq_data:
